In [2]:
import pandas as pd
import numpy as np


In [7]:
# Create a NumPy array from a list
array1 = np.array([8, 5, 3, 2, 1, 1])
print(array1)

array2 = np.array([[5, 1, 3], [1, 8, 7], [3, 7, 9]])
print(array2)

# import numpy as np

# Create a NumPy multi-dimensional array from nested lists
# array2 = np.array([[5, 1, 3], [1, 8, 7], [3, 7, 9]])
# Number of dimensions of array2
print(array2.ndim)
# Number of elemets (rows & columns in this instance) of array2
print(array2.shape)

print(np.sort(array1))

[8 5 3 2 1 1]
[[5 1 3]
 [1 8 7]
 [3 7 9]]
2
(3, 3)
[1 1 2 3 5 8]


In [16]:
# import numpy as np

# Create a NumPy array from a list
# array1 = np.array([8, 5, 3, 2, 1, 1])
# Split array1 into three separate arrays
newarray1 = np.array_split(array1, 3)
print(newarray1)

# import numpy as np

# Create a NumPy multi-dimensional array from nested lists
# array2 = np.array([[5, 1, 3], [1, 8, 7], [3, 7, 9]])
print('Mean of array2:', np.mean(array2))
print('Standard Deviation of array2:', np.std(array2))
print('Sum of array2:', np.sum(array2))

print('Mean of elements in axis 0 of array2:', np.mean(array2, axis=0))
print('Mean of elements in axis 1 of array2:', np.mean(array2, axis=1))

fruit_color = ["red", "yellow", "green", "green"]

custom_fruit_labels = pd.Series(["apple", "banana", "avocado", "honey dew"], index = fruit_color)

print(custom_fruit_labels)

[array([8, 5]), array([3, 2]), array([1, 1])]
Mean of array2: 4.888888888888889
Standard Deviation of array2: 2.8458329944145997
Sum of array2: 44
Mean of elements in axis 0 of array2: [3.         5.33333333 6.33333333]
Mean of elements in axis 1 of array2: [3.         5.33333333 6.33333333]
red           apple
yellow       banana
green       avocado
green     honey dew
dtype: object
